print("Welcome to the tip calculator.")
print("What as the total bill?")
total = input()
print("What percentage tip would you like to give?")
tip = "1." + input()
total = int(total) * float(tip)
print("How many people to split the bill?")
split = input()
total = total // int(split)
print(f"Each person should pay: ${round(total,2)}")